[package]
name = "liveclimbers"
version = "0.1.0"
edition = "2021"

[dependencies]
poise = "0.6.1"
tokio = { version = "1.43.0", features = ["rt-multi-thread", "macros"] }
tracing-subscriber = "0.3.19"
